#!/usr/bin/env bash
# Display to infinity and beyond with sleep 2 between iteration. 

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM
  trap 'echo "I have been killed by the enemy!!!"' SIGINT
done
