#!/bin/bash

IFS=":"

while read -r username x userid groupid user_info home_directory shell; do
    password=$(awk -F'[/:]' '{print $2}' <<< "$x")
    full_name=$(cut -d ',' -f 5 <<< "$user_info")

    echo "The user $username is part of the $groupid gang, lives in
    $home_directory and rides $shell. $userid's place is protected by the passcode 
    $password, more info about the user here: $full_name"
done < /etc/passwd

IFS=$' \t\n'

